apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - podinfo.yaml
  - audiobookshelf.yaml
  - mosquitto.yaml
  - postgres.yaml
  - homeassistant.yaml
  - actual.yaml
 # - n8n.yaml
  #- wol.yaml
#  - calibre.yaml
#pi - penpot.yaml
  #- add-bot.yaml
  #- homectl.yaml
  #- hue-mqtt.yaml
  #- vikunja.yaml
  - sump-it.yaml
  - ingress-proxy.yaml
#- lifx-mqtt.yaml
#- tuya-mqtt.yaml
#- twinkly-mqtt.yaml
#- nordpool-mqtt.yaml
#- adb-mqtt.yaml
#- fruitiex-org.yaml
# - influxdb.yaml
#  - wger.yaml
#  - pinepods.yaml
  #- kavita.yaml
  - jellyfin.yaml
  - mealie.yaml
  - tuuli-portfolio-redirect.yaml