apiVersion: v1
kind: Service
metadata:
  name: neolink
  namespace: neolink
spec:
  type: LoadBalancer
  selector:
    app: neolink
  ports:
    - name: rtsp
      protocol: TCP
      port: 8554
      targetPort: 8554
