apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sparkyfitness
resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - persistentVolumes.yaml
  - ingress.yaml
