apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-db
  namespace: sparkyfitness
spec:
  selector:
    app: sparkyfitness-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-server
  namespace: sparkyfitness
spec:
  selector:
    app: sparkyfitness-server
  ports:
  - port: 3010
    targetPort: 3010
---
apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-frontend
  namespace: sparkyfitness
spec:
  selector:
    app: sparkyfitness-frontend
  ports:
  - port: 80
    targetPort: 80
