resources:
  - actual/
  - audiobookshelf/
  - calibre/
  - homeassistant/
  - influxdb/
  - ingress-proxy/
  - kavita/
  - mealie/
  - mosquitto/
  - n8n/
  - neolink/
  - penpot/
  - pinepods/
  - podinfo/
  - postgres/
  - sump-it/
